import React from "react";
import { Badge, Card, Text, makeStyles, mergeClasses, tokens } from "@fluentui/react-components";
import type { Json } from "@gik/kernel";
import { runDeclarativeValidators } from "@gik/evaluators";
import type { ProjectionView } from "@gik/react";

import { trialNode, type ComponentDescription, type ComponentValidationReport, type DeclarativeComponentDefinition } from "../../shared/definition";
import { componentRootProps, componentStylePropsSchema, records, textAt, type BadgeColor } from "../../shared/component";

export const EVIDENCE_TRAIL_SEMANTIC_TOKENS = ["corroborating", "contradicting", "uncertain", "primary", "context"] as const;
export const EVIDENCE_TRAIL_VARIANTS = ["detailed", "compact"] as const;
type EvidenceToken = typeof EVIDENCE_TRAIL_SEMANTIC_TOKENS[number];
const schema = {
  $schema: "http://json-schema.org/draft-07/schema#", type: "object", additionalProperties: false, required: ["evidence", "spec"],
  properties: { ...componentStylePropsSchema, evidence: { type: "array", items: { type: "object" } }, variant: { enum: EVIDENCE_TRAIL_VARIANTS }, spec: { type: "object", additionalProperties: false, required: ["fields"], properties: {
    title: { type: "string" }, emptyText: { type: "string" }, fields: { type: "object", additionalProperties: false, required: ["title", "source"], properties: { id: { type: "string", minLength: 1 }, title: { type: "string", minLength: 1 }, source: { type: "string", minLength: 1 }, excerpt: { type: "string", minLength: 1 }, timestamp: { type: "string", minLength: 1 }, tone: { type: "string", minLength: 1 } } }, toneMap: { type: "object", additionalProperties: { enum: EVIDENCE_TRAIL_SEMANTIC_TOKENS } },
  } } },
} as const;
type EvidenceSpec = { title?: string; emptyText?: string; fields: { id?: string; title: string; source: string; excerpt?: string; timestamp?: string; tone?: string }; toneMap?: Record<string, EvidenceToken> };
const useStyles = makeStyles({ root: { display: "grid", gap: tokens.spacingVerticalM }, trail: { display: "grid", gap: tokens.spacingVerticalS, borderLeft: `${tokens.strokeWidthThick} solid ${tokens.colorNeutralStroke2}`, paddingLeft: tokens.spacingHorizontalL }, item: { display: "grid", gap: tokens.spacingVerticalS }, compactItem: { gridTemplateColumns: "minmax(0, 1fr) auto", alignItems: "center" }, header: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: tokens.spacingHorizontalS }, meta: { color: tokens.colorNeutralForeground3 }, excerpt: { color: tokens.colorNeutralForeground2, borderLeft: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`, paddingLeft: tokens.spacingHorizontalM } });
function color(token: EvidenceToken): BadgeColor { if (token === "corroborating") return "success"; if (token === "contradicting") return "danger"; if (token === "uncertain") return "warning"; if (token === "primary") return "brand"; return "informative"; }
export const EvidenceTrail: ProjectionView = ({ node }) => {
  const styles = useStyles(); const evidence = records(node.props.evidence); const spec = (node.props.spec ?? {}) as EvidenceSpec; const compact = (node.props.variant ?? "detailed") === "compact";
  if (!spec.fields || evidence.length === 0) return <Text {...componentRootProps(node)}>{spec.emptyText ?? "No evidence available."}</Text>;
  return <section {...componentRootProps(node, styles.root)} aria-label={spec.title ?? "Evidence trail"}>{spec.title ? <Text weight="semibold" size={500}>{spec.title}</Text> : null}<div className={styles.trail}>{evidence.map((item, index) => { const toneValue = textAt(item, spec.fields.tone); const token = toneValue ? spec.toneMap?.[toneValue] : undefined; return <Card className={mergeClasses(styles.item, compact && styles.compactItem)} appearance="outline" key={textAt(item, spec.fields.id) || `${textAt(item, spec.fields.title)}-${index}`}>
    <div><div className={styles.header}><Text weight="semibold">{textAt(item, spec.fields.title)}</Text>{token ? <Badge appearance="tint" color={color(token)}>{toneValue}</Badge> : null}</div><Text className={styles.meta} size={200}>{[textAt(item, spec.fields.source), textAt(item, spec.fields.timestamp)].filter(Boolean).join(" · ")}</Text>{!compact && spec.fields.excerpt && textAt(item, spec.fields.excerpt) ? <Text className={styles.excerpt}>{textAt(item, spec.fields.excerpt)}</Text> : null}</div>
  </Card>; })}</div></section>;
};
const description: ComponentDescription = { capability: "semantic:evidence-trail", summary: "Shows an ordered chain of sourced evidence with excerpts and semantic evidentiary roles.", dataProp: "evidence", events: [], semanticTokens: EVIDENCE_TRAIL_SEMANTIC_TOKENS, defaultVariant: "detailed", variants: [{ value: "detailed", summary: "Source metadata and excerpts in an explicit evidence chain.", useWhen: ["Users must inspect why evidence supports a conclusion", "Excerpts are short and important"] }, { value: "compact", summary: "Source and title rows without excerpts.", useWhen: ["Evidence is secondary to a summary", "Users need a quick provenance scan"] }], authoring: { useWhen: ["Findings must be traceable to ordered sources", "Evidence roles such as corroborating or contradicting matter"], avoidWhen: ["Exact source lines require inline annotations; use annotated-source-excerpt", "Records are merely chronological; use timeline"], rules: ["Preserve source order intentionally", "Include stable evidence IDs when available", "Do not invent excerpts or provenance", "Map evidentiary roles only to recognized tokens"] } };
export function describeEvidenceTrail() { return description; }
export function getEvidenceTrailSchema(): Record<string, unknown> { return schema as unknown as Record<string, unknown>; }
export function validateEvidenceTrail(props: unknown): ComponentValidationReport { return runDeclarativeValidators([{ kind: "ajv-schema", schema: getEvidenceTrailSchema(), message: "Invalid semantic:evidence-trail props", code: "semantic-evidence-trail-schema" }], props as Json); }
export function materializeEvidenceTrailTrial() { return trialNode("semantic:evidence-trail", { variant: "detailed", evidence: [{ id: "ev-1", title: "Unfamiliar device registration", source: "Identity audit log", at: "09:14 UTC", excerpt: "Device credential registered after the first anomalous sign-in.", role: "corroborates" }, { id: "ev-2", title: "Conditional access challenge", source: "Sign-in log", at: "09:16 UTC", excerpt: "Challenge originated from the same network and user session.", role: "primary" }], spec: { title: "Evidence trail", fields: { id: "id", title: "title", source: "source", timestamp: "at", excerpt: "excerpt", tone: "role" }, toneMap: { corroborates: "corroborating", primary: "primary" } } }); }
export const evidenceTrailDefinition: DeclarativeComponentDefinition = { capability: description.capability, version: "1.0.0", summary: description.summary, dataProp: description.dataProp, events: description.events, semanticTokens: description.semanticTokens, defaultVariant: description.defaultVariant, variants: description.variants, authoring: description.authoring, component: EvidenceTrail, describe: describeEvidenceTrail, getSchema: getEvidenceTrailSchema, validate: validateEvidenceTrail, materializeTrial: materializeEvidenceTrailTrial };