import React from "react";
import { Badge, Text, makeStyles, mergeClasses, tokens } from "@fluentui/react-components";
import type { Json } from "@gik/kernel";
import { runDeclarativeValidators } from "@gik/evaluators";
import type { ProjectionView } from "@gik/react";

import { trialNode, type ComponentDescription, type ComponentValidationReport, type DeclarativeComponentDefinition } from "../definition";
import { componentRootProps, componentStylePropsSchema, records, textAt, type BadgeColor } from "../shared";

export const ANNOTATED_SOURCE_EXCERPT_SEMANTIC_TOKENS = ["highlight", "warning", "critical", "context", "positive"] as const;
export const ANNOTATED_SOURCE_EXCERPT_VARIANTS = ["annotated", "compact"] as const;
type SourceToken = typeof ANNOTATED_SOURCE_EXCERPT_SEMANTIC_TOKENS[number];
const schema = {
  $schema: "http://json-schema.org/draft-07/schema#", type: "object", additionalProperties: false, required: ["lines", "spec"],
  properties: { ...componentStylePropsSchema, lines: { type: "array", items: { type: "object" } }, variant: { enum: ANNOTATED_SOURCE_EXCERPT_VARIANTS }, spec: { type: "object", additionalProperties: false, required: ["fields"], properties: {
    title: { type: "string" }, language: { type: "string" }, sourceLabel: { type: "string" }, emptyText: { type: "string" }, fields: { type: "object", additionalProperties: false, required: ["number", "text"], properties: { number: { type: "string", minLength: 1 }, text: { type: "string", minLength: 1 }, annotation: { type: "string", minLength: 1 }, tone: { type: "string", minLength: 1 } } }, toneMap: { type: "object", additionalProperties: { enum: ANNOTATED_SOURCE_EXCERPT_SEMANTIC_TOKENS } },
  } } },
} as const;
type SourceSpec = { title?: string; language?: string; sourceLabel?: string; emptyText?: string; fields: { number: string; text: string; annotation?: string; tone?: string }; toneMap?: Record<string, SourceToken> };
const useStyles = makeStyles({ root: { display: "grid", gap: tokens.spacingVerticalS, minWidth: 0 }, header: { display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: tokens.spacingHorizontalM }, source: { color: tokens.colorNeutralForeground3 }, code: { overflowX: "auto", border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`, borderRadius: tokens.borderRadiusMedium, backgroundColor: tokens.colorNeutralBackground3, fontFamily: tokens.fontFamilyMonospace }, line: { display: "grid", gridTemplateColumns: "3rem minmax(12rem, 1fr) minmax(10rem, .7fr)", minHeight: "2rem", borderBottom: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke3}` }, compactLine: { gridTemplateColumns: "3rem minmax(12rem, 1fr)" }, number: { color: tokens.colorNeutralForeground4, textAlign: "right", padding: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalS}`, userSelect: "none" }, text: { whiteSpace: "pre", padding: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalM}` }, annotation: { display: "flex", alignItems: "center", gap: tokens.spacingHorizontalS, borderLeft: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`, padding: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalM}`, fontFamily: tokens.fontFamilyBase } });
function color(token: SourceToken): BadgeColor { if (token === "critical") return "danger"; if (token === "warning") return "warning"; if (token === "positive") return "success"; if (token === "highlight") return "brand"; return "informative"; }
export const AnnotatedSourceExcerpt: ProjectionView = ({ node }) => {
  const styles = useStyles(); const lines = records(node.props.lines); const spec = (node.props.spec ?? {}) as SourceSpec; const compact = (node.props.variant ?? "annotated") === "compact";
  if (!spec.fields || lines.length === 0) return <Text {...componentRootProps(node)}>{spec.emptyText ?? "No source excerpt available."}</Text>;
  return <figure {...componentRootProps(node, styles.root)} aria-label={spec.title ?? "Annotated source excerpt"}><figcaption className={styles.header}><div>{spec.title ? <Text weight="semibold">{spec.title}</Text> : null}{spec.language ? <Badge appearance="outline">{spec.language}</Badge> : null}</div>{spec.sourceLabel ? <Text className={styles.source} size={200}>{spec.sourceLabel}</Text> : null}</figcaption><div className={styles.code}>{lines.map((line, index) => { const annotation = textAt(line, spec.fields.annotation); const toneValue = textAt(line, spec.fields.tone); const token = toneValue ? spec.toneMap?.[toneValue] : undefined; return <div className={mergeClasses(styles.line, compact && styles.compactLine)} key={`${textAt(line, spec.fields.number)}-${index}`}><Text className={styles.number}>{textAt(line, spec.fields.number)}</Text><Text className={styles.text}>{textAt(line, spec.fields.text)}</Text>{!compact ? <div className={styles.annotation}>{token ? <Badge appearance="tint" color={color(token)}>{toneValue}</Badge> : null}{annotation ? <Text size={200}>{annotation}</Text> : null}</div> : null}</div>; })}</div></figure>;
};
const description: ComponentDescription = { capability: "semantic:annotated-source-excerpt", summary: "Displays exact source lines with stable line numbers and optional inline semantic annotations.", dataProp: "lines", events: [], semanticTokens: ANNOTATED_SOURCE_EXCERPT_SEMANTIC_TOKENS, defaultVariant: "annotated", variants: [{ value: "annotated", summary: "Source lines and a dedicated annotation column.", useWhen: ["Users must inspect commentary beside exact lines", "Annotations are central evidence"] }, { value: "compact", summary: "Line-numbered source without annotation details.", useWhen: ["The excerpt is supporting context", "Annotations are summarized elsewhere"] }], authoring: { useWhen: ["Exact source wording and line references matter", "Findings attach to individual lines"], avoidWhen: ["Evidence spans independent sources; use evidence-trail", "Content is explanatory prose rather than quoted source; use narrative-section"], rules: ["Preserve source text exactly", "Supply stable displayed line numbers", "Do not execute or syntax-highlight source content", "Map annotation tones only to recognized tokens"] } };
export function describeAnnotatedSourceExcerpt() { return description; }
export function getAnnotatedSourceExcerptSchema(): Record<string, unknown> { return schema as unknown as Record<string, unknown>; }
export function validateAnnotatedSourceExcerpt(props: unknown): ComponentValidationReport { return runDeclarativeValidators([{ kind: "ajv-schema", schema: getAnnotatedSourceExcerptSchema(), message: "Invalid semantic:annotated-source-excerpt props", code: "semantic-annotated-source-excerpt-schema" }], props as Json); }
export function materializeAnnotatedSourceExcerptTrial() { return trialNode("semantic:annotated-source-excerpt", { variant: "annotated", lines: [{ line: 41, text: "if (riskScore >= containmentThreshold) {", note: "Containment threshold reached", tone: "attention" }, { line: 42, text: "  await disableIdentity(subjectId);", note: "External effect boundary", tone: "critical" }, { line: 43, text: "}", note: "", tone: "context" }], spec: { title: "Containment policy", language: "TypeScript", sourceLabel: "policies/containment.ts", fields: { number: "line", text: "text", annotation: "note", tone: "tone" }, toneMap: { attention: "warning", critical: "critical", context: "context" } } }); }
export const annotatedSourceExcerptDefinition: DeclarativeComponentDefinition = { capability: description.capability, version: "1.0.0", summary: description.summary, dataProp: description.dataProp, events: description.events, semanticTokens: description.semanticTokens, defaultVariant: description.defaultVariant, variants: description.variants, authoring: description.authoring, component: AnnotatedSourceExcerpt, describe: describeAnnotatedSourceExcerpt, getSchema: getAnnotatedSourceExcerptSchema, validate: validateAnnotatedSourceExcerpt, materializeTrial: materializeAnnotatedSourceExcerptTrial };