import React from "react";
import { Badge, Card, Text, makeStyles, tokens } from "@fluentui/react-components";
import type { Json } from "@gik/kernel";
import { runDeclarativeValidators } from "@gik/evaluators";
import type { ProjectionView } from "@gik/react";

import { trialNode, type ComponentDescription, type ComponentValidationReport, type DeclarativeComponentDefinition } from "../definition";
import { asRecord, records, textAt, type BadgeColor } from "../shared";

export const SEMANTIC_GRAPH_SEMANTIC_TOKENS = ["central", "related", "risk", "positive", "neutral"] as const;
export const SEMANTIC_GRAPH_VARIANTS = ["network", "relations"] as const;
type GraphToken = typeof SEMANTIC_GRAPH_SEMANTIC_TOKENS[number];
const schema = {
  $schema: "http://json-schema.org/draft-07/schema#", type: "object", additionalProperties: false, required: ["graph", "spec"],
  properties: {
    graph: { type: "object", additionalProperties: false, required: ["nodes", "edges"], properties: { nodes: { type: "array", items: { type: "object" } }, edges: { type: "array", items: { type: "object" } } } },
    variant: { enum: SEMANTIC_GRAPH_VARIANTS },
    spec: { type: "object", additionalProperties: false, required: ["nodeFields", "edgeFields"], properties: {
      title: { type: "string" }, description: { type: "string" }, emptyText: { type: "string" },
      nodeFields: { type: "object", additionalProperties: false, required: ["id", "label"], properties: { id: { type: "string", minLength: 1 }, label: { type: "string", minLength: 1 }, detail: { type: "string", minLength: 1 }, tone: { type: "string", minLength: 1 } } },
      edgeFields: { type: "object", additionalProperties: false, required: ["source", "target"], properties: { source: { type: "string", minLength: 1 }, target: { type: "string", minLength: 1 }, label: { type: "string", minLength: 1 } } },
      toneMap: { type: "object", additionalProperties: { enum: SEMANTIC_GRAPH_SEMANTIC_TOKENS } },
    } },
  },
} as const;
type GraphSpec = { title?: string; description?: string; emptyText?: string; nodeFields: { id: string; label: string; detail?: string; tone?: string }; edgeFields: { source: string; target: string; label?: string }; toneMap?: Record<string, GraphToken> };
const useStyles = makeStyles({ root: { display: "grid", gap: tokens.spacingVerticalM, minWidth: 0 }, header: { display: "grid", gap: tokens.spacingVerticalXXS }, description: { color: tokens.colorNeutralForeground3 }, network: { width: "100%", minHeight: "20rem", backgroundColor: tokens.colorNeutralBackground2, border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`, borderRadius: tokens.borderRadiusMedium }, relations: { display: "grid", gap: tokens.spacingVerticalS }, relation: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) auto minmax(0, 1fr)", alignItems: "center", gap: tokens.spacingHorizontalM }, endpoint: { display: "grid", gap: tokens.spacingVerticalXXS, minWidth: 0 }, target: { textAlign: "right" }, relationLabel: { color: tokens.colorNeutralForeground3, textAlign: "center" } });
function fill(token: GraphToken | undefined): string { if (token === "central") return tokens.colorBrandBackground; if (token === "risk") return tokens.colorPaletteRedBackground3; if (token === "positive") return tokens.colorPaletteGreenBackground3; if (token === "related") return tokens.colorPaletteLightTealBackground2; return tokens.colorNeutralBackground4; }
function foreground(token: GraphToken | undefined): string { return token === "central" ? tokens.colorNeutralForegroundOnBrand : tokens.colorNeutralForeground1; }
function badgeColor(token: GraphToken | undefined): BadgeColor { if (token === "central") return "brand"; if (token === "risk") return "danger"; if (token === "positive") return "success"; return "informative"; }
export const SemanticGraph: ProjectionView = ({ node }) => {
  const styles = useStyles(); const graph = asRecord(node.props.graph); const nodes = records(graph.nodes); const edges = records(graph.edges); const spec = (node.props.spec ?? {}) as GraphSpec; const variant = node.props.variant ?? "network";
  if (!spec.nodeFields || !spec.edgeFields || nodes.length === 0) return <Text>{spec.emptyText ?? "No graph data available."}</Text>;
  const byId = new Map(nodes.map((item) => [textAt(item, spec.nodeFields.id), item]));
  const positions = new Map(nodes.map((item, index) => { const angle = (Math.PI * 2 * index) / nodes.length - Math.PI / 2; const radius = nodes.length <= 3 ? 105 : 135; return [textAt(item, spec.nodeFields.id), { x: 320 + Math.cos(angle) * radius, y: 180 + Math.sin(angle) * radius }]; }));
  return <section className={styles.root} aria-label={spec.title ?? "Semantic graph"}><div className={styles.header}>{spec.title ? <Text weight="semibold" size={500}>{spec.title}</Text> : null}{spec.description ? <Text className={styles.description}>{spec.description}</Text> : null}</div>{variant === "relations" ? <div className={styles.relations}>{edges.map((edge, index) => { const source = byId.get(textAt(edge, spec.edgeFields.source)); const target = byId.get(textAt(edge, spec.edgeFields.target)); if (!source || !target) return null; const sourceToneValue = textAt(source, spec.nodeFields.tone); const targetToneValue = textAt(target, spec.nodeFields.tone); return <Card appearance="outline" className={styles.relation} key={index}><div className={styles.endpoint}><Text weight="semibold">{textAt(source, spec.nodeFields.label)}</Text>{sourceToneValue ? <Badge appearance="tint" color={badgeColor(spec.toneMap?.[sourceToneValue])}>{sourceToneValue}</Badge> : null}</div><Text className={styles.relationLabel} size={200}>{textAt(edge, spec.edgeFields.label) || "related to"}</Text><div className={`${styles.endpoint} ${styles.target}`}><Text weight="semibold">{textAt(target, spec.nodeFields.label)}</Text>{targetToneValue ? <Badge appearance="tint" color={badgeColor(spec.toneMap?.[targetToneValue])}>{targetToneValue}</Badge> : null}</div></Card>; })}</div> : <svg className={styles.network} viewBox="0 0 640 360" role="img"><title>{spec.title ?? "Semantic graph"}</title><desc>{spec.description ?? `${nodes.length} nodes and ${edges.length} relationships`}</desc>{edges.map((edge, index) => { const source = positions.get(textAt(edge, spec.edgeFields.source)); const target = positions.get(textAt(edge, spec.edgeFields.target)); if (!source || !target) return null; const midX = (source.x + target.x) / 2; const midY = (source.y + target.y) / 2; return <g key={`edge-${index}`}><line x1={source.x} y1={source.y} x2={target.x} y2={target.y} stroke={tokens.colorNeutralStroke1} strokeWidth="2" /><text x={midX} y={midY - 6} textAnchor="middle" fill={tokens.colorNeutralForeground3} fontSize="11">{textAt(edge, spec.edgeFields.label)}</text></g>; })}{nodes.map((item) => { const id = textAt(item, spec.nodeFields.id); const position = positions.get(id)!; const toneValue = textAt(item, spec.nodeFields.tone); const token = toneValue ? spec.toneMap?.[toneValue] : undefined; const label = textAt(item, spec.nodeFields.label); return <g key={id}><circle cx={position.x} cy={position.y} r="44" fill={fill(token)} stroke={tokens.colorNeutralStroke1} strokeWidth="2"><title>{`${label}${spec.nodeFields.detail ? `: ${textAt(item, spec.nodeFields.detail)}` : ""}`}</title></circle><text x={position.x} y={position.y + 4} textAnchor="middle" fill={foreground(token)} fontSize="13" fontWeight="600">{label.length > 15 ? `${label.slice(0, 14)}…` : label}</text></g>; })}</svg>}</section>;
};
const description: ComponentDescription = { capability: "semantic:semantic-graph", summary: "Shows explicit semantic relationships between identified entities as a network or relation list.", dataProp: "graph", events: [], semanticTokens: SEMANTIC_GRAPH_SEMANTIC_TOKENS, defaultVariant: "network", variants: [{ value: "network", summary: "Node-link network for understanding topology and clusters.", useWhen: ["Relationship shape is the primary insight", "The graph is small enough to inspect without interaction"] }, { value: "relations", summary: "Accessible ordered list of source-relation-target statements.", useWhen: ["Precise relationship reading matters more than topology", "The surface is narrow or assistive-technology focused"] }], authoring: { useWhen: ["Entities are connected by explicit semantic relationships", "Users need topology or relationship statements"], avoidWhen: ["Only grouped populations matter; use entity-constellation", "The graph requires force layout, zooming, or large-scale exploration; use a specialized graph capability"], rules: ["Provide unique stable node IDs", "Reference only declared node IDs from edges", "Keep network graphs small", "Use relation labels as concise predicates", "Map node tones only to recognized graph tokens"] } };
export function describeSemanticGraph() { return description; }
export function getSemanticGraphSchema(): Record<string, unknown> { return schema as unknown as Record<string, unknown>; }
export function validateSemanticGraph(props: unknown): ComponentValidationReport { return runDeclarativeValidators([
  { kind: "ajv-schema", schema: getSemanticGraphSchema(), message: "Invalid semantic:semantic-graph props", code: "semantic-graph-schema" },
  { kind: "jsonata", expr: "($field := data.spec.nodeFields.id; $ids := data.graph.nodes.$lookup($, $field); $count($ids) = $count($distinct($ids)))", message: "Semantic graph node IDs must be unique", code: "semantic-graph-unique-node-id" },
  { kind: "jsonata", expr: "($nodeField := data.spec.nodeFields.id; $sourceField := data.spec.edgeFields.source; $targetField := data.spec.edgeFields.target; $ids := data.graph.nodes.$lookup($, $nodeField); $count(data.graph.edges[$lookup($, $sourceField) in $ids and $lookup($, $targetField) in $ids]) = $count(data.graph.edges))", message: "Semantic graph edges must reference declared node IDs", code: "semantic-graph-edge-reference" },
], props as Json); }
export function materializeSemanticGraphTrial() { return trialNode("semantic:semantic-graph", { variant: "network", graph: { nodes: [{ id: "identity", label: "Admin identity", detail: "Affected principal", role: "focus" }, { id: "device", label: "New device", detail: "Registered credential", role: "risk" }, { id: "application", label: "Finance app", detail: "Accessed resource", role: "related" }, { id: "control", label: "Access policy", detail: "Triggered challenge", role: "positive" }], edges: [{ from: "identity", to: "device", relation: "registered" }, { from: "identity", to: "application", relation: "accessed" }, { from: "control", to: "identity", relation: "challenged" }] }, spec: { title: "Incident relationships", description: "Entities linked by observed activity", nodeFields: { id: "id", label: "label", detail: "detail", tone: "role" }, edgeFields: { source: "from", target: "to", label: "relation" }, toneMap: { focus: "central", risk: "risk", related: "related", positive: "positive" } } }); }
export const semanticGraphDefinition: DeclarativeComponentDefinition = { capability: description.capability, version: "1.0.0", summary: description.summary, dataProp: description.dataProp, events: description.events, semanticTokens: description.semanticTokens, defaultVariant: description.defaultVariant, variants: description.variants, authoring: description.authoring, component: SemanticGraph, describe: describeSemanticGraph, getSchema: getSemanticGraphSchema, validate: validateSemanticGraph, materializeTrial: materializeSemanticGraphTrial };